name: Ratchet Deadlocked (USA)
sha1: accfca45948d59a16d932443ae7e201d0f0cabf0
options:
  basename: SCUS_974.65
  target_path: config/SCUS_974.65.rom
  elf_path: build/SCUS_974.65
  base_path: ../
  platform: ps2
  compiler: EEGCC

  gp_value: 0x0022597F
  # ld_gp_expression:

  asm_path: code/asm
  src_path: code/
  build_path: build
  data_path: build

  ld_script_path:  config/SCUS_974.65.ld
  # ld_dependencies: True
  # ld_wildcard_sections: True
  # ld_bss_contains_common: True
  # create_asm_dependencies: True

  find_file_boundaries: False

  o_as_suffix: True


  disasm_unknown: True
  pair_rodata_to_text: False
  generate_asm_macros_files: false

  asm_inc_header: |
    .include "macro.inc"

  check_consecutive_segment_types: False
  do_c_func_detection: False
  ld_wildcard_sections: True

  subalign: 8

  symbol_addrs_path:
    -  config/symbols.txt
  reloc_addrs_path:
    -  config/reloc_addrs.txt

  undefined_funcs_auto_path: build/undefined_funcs_auto.txt
  undefined_syms_auto_path: build/undefined_syms_auto.txt

  # extensions_path: tools/splat_ext

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 0 # 2
  data_string_guesser_level: 0 # 2

  named_regs_for_c_funcs: False

  # section_order:
  #   - .vutext
  #   - .lit
  #   - .bss
  #   - .data
  #   - .text

  # auto_link_sections:
  #   - .lit
  #   - .bss
  #   - .data

segments:
  - name: vutext
    type: code
    start: 0x000000
    vram: 0x00100080
    subsegments:
      - [0x000000, textbin, vutext/000000] # .vutext

  - name: core.text
    type: code
    start: 0x01A100
    vram: 0x0011A180
    bss_size: 0x78AB8
    subsegments:
      - [0x01A100, asm, core.text/01A100]      # core.text
      
      - [0x576b8, cpp, game/boot]
      - [0x57ce0, c, 989snd/ee/989snd]
      - [0x59928, cpp, game/permcb]
      - [0x59980, cpp, game/wad]
      - [0x59ba8, cpp, game/gameglobals]


      - [0x063B00, bin, core.data/063B00]      # core.data
      - [0x091E80, rodata, core.data/091E80]   # core.rdata
      - { type: bss, vram: 0x001A5180, name: cod/001A5180 } # core.bss

  - name: core.lit
    type: data
    start: 0x11DC00
    vram: 0x0021DC80
    subsegments:
      - [0x11DC00, data, core.lit/11DC00]

  - name: lit
    type: data
    start: 0x11E100
    vram: 0x0021E180
    subsegments:
      - [0x11E100, data, lit/11E100]

  - name: bss
    type: data
    start: 0x121000
    vram: 0x00221080
    bss_size: 0x1A4908
    subsegments:
      - { type: bss, vram: 0x00221080, name: bss/00221080 }

  - name: data
    type: data
    start: 0x2C5980
    vram: 0x003C5A00
    subsegments:
      - [0x2C5980, data, data/2C5980]

  - name: lvl.vtbl
    type: code
    start: 0x2F0E00
    vram: 0x003F0E80
    bss_size: 0x0
    subalign: null
    subsegments:
      - [0x2F0E00, rodata, lvl.vtbl/2F0E00]

  - name: lvl.camvtbl
    type: code
    start: 0x2F0E80
    vram: 0x003F0F00
    bss_size: 0x0
    subalign: null
    subsegments:
      - [0x2F0E80, rodata, lvl.camvtbl/2F0E80]

  - name: lvl.sndvtbl
    type: code
    start: 0x2F0F00
    vram: 0x003F0F80
    bss_size: 0x0
    subalign: null
    subsegments:
      - [0x2F0F00, rodata, lvl.sndvtbl/2F0F00]

  - name: text
    type: code
    start: 0x2F0F80
    vram: 0x003F1000
    bss_size: 0x0
    subalign: null
    subsegments:
      - [0x2F0F80, asm, text/2F0F80]

  - name: patch.data
    type: code
    start: 0x44D680
    vram: 0x0054D700
    bss_size: 0x0
    subalign: null
    subsegments:
      - [0x44D680, data, patch.data/44D680]

  - name: net.text
    type: code
    start: 0x44E000
    vram: 0x01E9A000
    subsegments:
      - [0x44E000, asm, net.text/44E000]

  - name: net.nostomp
    type: code
    start: 0x4E5380
    vram: 0x01F31380
    subsegments:
      - [0x4E5380, asm, net.nostomp/4E5380]

  - [0x4EBFA0]
